import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="robots" content="index, follow" />
        <link rel="canonical" href="http://google.com/" />
      </Head>

      <Link href="/tv-shows/avengers">
        <button className="btn d-flex align-items-center">
          Go to TV Shows{" "}
          <span className={`text-white ml-1 ${styles.arrowRight}`}>
            {" "}
            &rarr;{" "}
          </span>{" "}
        </button>
      </Link>
    </div>
  );
}
